version: "3.9"

services:
  stt:
    build: .
    container_name: Arabic-STT-Diarization
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - hf-cache:/root/.cache/huggingface
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped

volumes:
  hf-cache:
  torch-cache: